{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "MaskDetectorHelm.serviceAccountName" . }}
  labels:
{{ include "MaskDetectorHelm.labels" . | indent 4 }}
{{- end -}}
